### PR TITLE
redis time series module

### PR DESCRIPTION
**Pull request by AvitalFineRedis**

### CODE REVIEW

**Comment by AvitalFineRedis** [comment]
@chayim Ready for review

Not sure if the `testPool` is necessary...
Also need to update the redisTimeSerie module in `redismod` to a newer version

**Comment by AvitalFineRedis** [comment]
@chayim ready

**Comment by chayim** [comment]
@AvitalFineRedis Can you see what we can do to remove the VERSION bits from this PR? We shouldn't need an internal version of redistimeseries IMHO. I recognize that the module had it - but now in redisplus.. no need.

**Comment by AvitalFineRedis** [comment]
@chayim, Some of the linters warning I tried to fix [here](https://github.com/RedisLabsModules/redisplus-py/pull/31), but still it is complaining about missing docstring in each `__init__` file (can't get enough)

**Pull request merged**
